export enum DmSessionError {
  NOT_FOUND = 'DM_SESSION_NOT_FOUND',
  UNAUTHORIZED = 'DM_SESSION_UNAUTHORIZED',
  INVALID_PROMPT = 'DM_SESSION_INVALID_PROMPT',
  INVALID_CHARACTERS = 'DM_SESSION_INVALID_CHARACTERS',
  INVALID_INPUT = 'DM_SESSION_INVALID_INPUT',
  NOT_INITIALIZING = 'DM_SESSION_NOT_INITIALIZING',
  NOT_ACTIVE = 'DM_SESSION_NOT_ACTIVE',
  ALREADY_ENDED = 'DM_SESSION_ALREADY_ENDED',
  ALREADY_DELETED = 'DM_SESSION_ALREADY_DELETED',
  MODEL_ERROR = 'DM_SESSION_MODEL_ERROR',
}
