export enum CharacterError {
  NOT_FOUND = 'CHARACTER_NOT_FOUND',
  NOT_A_MEMBER = 'CHARACTER_NOT_A_MEMBER',
  ALREADY_EXISTS = 'CHARACTER_ALREADY_EXISTS',
  CAMPAIGN_NOT_ACTIVE = 'CHARACTER_CAMPAIGN_NOT_ACTIVE',
  ASSET_NOT_IN_CAMPAIGN = 'CHARACTER_ASSET_NOT_IN_CAMPAIGN',
  INVALID_STATS = 'CHARACTER_INVALID_STATS',
  UNAUTHORIZED = 'CHARACTER_UNAUTHORIZED',
}
