export enum PackError {
  SLUG_ALREADY_EXISTS = 'SLUG_ALREADY_EXISTS',
  NOT_FOUND = 'PACK_NOT_FOUND',
  ALREADY_SUSPENDED = 'PACK_ALREADY_SUSPENDED',
  NOT_SUSPENDED = 'PACK_NOT_SUSPENDED',
  CANNOT_DELETE_SRD = 'CANNOT_DELETE_SRD_PACK',
}

export enum AssetError {
  NOT_FOUND = 'ASSET_NOT_FOUND',
  PACK_NOT_FOUND = 'PACK_NOT_FOUND',
  ALREADY_EXISTS = 'ASSET_ALREADY_EXISTS',
  INVALID_TYPE = 'INVALID_ASSET_TYPE',
}
