export enum CampaignError {
  NOT_FOUND = 'CAMPAIGN_NOT_FOUND',
  INVALID_STATUS = 'INVALID_CAMPAIGN_STATUS',
  INVALID_STATUS_TRANSITION = 'INVALID_CAMPAIGN_STATUS_TRANSITION',
  NOT_OWNER = 'CAMPAIGN_NOT_OWNER',
  SLUG_ALREADY_EXISTS = 'CAMPAIGN_NAME_ALREADY_EXISTS',
  ALREADY_EXISTS = 'CAMPAIGN_MEMBER_ALREADY_EXISTS',
  UNAUTHORIZED = 'CAMPAIGN_UNAUTHORIZED',
}
